export const Clist = [
    {
        id:0,
        image:"./images/GetShreked.jpeg",
        title:"Sheron",
    },
    {
        id:1,
        image:"./images/NinJesus.jpeg",
        title:"KettleMan",
    },
    {
        id:2,
        image:"./images/Barben.jpg",
        title:"Mansi",
    },
    {
        id:3,
        image:"./images/BhuJogi.jpg",
        title:"HelpMe",
    },
];